services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kea_cars_dev
    networks:
      - appnet
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb-volume:/data/db
    networks:
      - appnet
    command: ["mongod", "--bind_ip_all"]

  backend:
    image: kea_car_backend:v1.0
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_NAME=kea_cars_dev
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=cars
    depends_on:
      - mysql
      - mongodb
    networks:
      - appnet
    volumes:
      - .:/app
    command: ["/app/scripts/start_and_restore.sh"]

networks:
  appnet:
    driver: bridge

volumes:
  mysql-data:
  mongodb-volume:
