name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download CPU log using curl
        run: |
          mkdir -p ./logs
          curl -L "https://staging.c7pixel.com/logs/cpu_mem_usage.log" -o ./logs/cpu_mem_usage.log
